version: 2
updates:
- package-ecosystem: pip
  directory: "/unrivalry"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.1
    - 3.3.2
    - 3.3.3
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: pytz
    versions:
    - "2020.5"
- package-ecosystem: npm
  directory: "/unrivalry"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
